name: E2E
#когда запускаем
on:
  push:
    branches:
      - main
  workflow_dispatch:
  #описываем джобы
jobs:
  e2e:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Install Node.js
        uses: actions/setup-node@v5
        with:
          node-version: lts/*
      - name: Install of packages
        run: npm i
      - name: установка браузеров
        run: npx playwright install --with-deps
      - name: запускаем тесыт
        run: npm t
